name: guess_the_footballer
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.3
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true