// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3e6_o62TJ9di1P78Zxg0ySTsUmGk71VI',
    appId: '1:852476349759:web:c2deaa621daf90e185178a',
    messagingSenderId: '852476349759',
    projectId: 'guess-the-footballer-db87f',
    authDomain: 'guess-the-footballer-db87f.firebaseapp.com',
    storageBucket: 'guess-the-footballer-db87f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUW2dMJNxOQT_Mxeo5zoI0sivPjL3KR58',
    appId: '1:852476349759:android:bfa92d974d9eca4485178a',
    messagingSenderId: '852476349759',
    projectId: 'guess-the-footballer-db87f',
    storageBucket: 'guess-the-footballer-db87f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl6Sai_rPGyIwzTIZFJh18DIs7F43_P3s',
    appId: '1:852476349759:ios:fcaf418ab9a9427a85178a',
    messagingSenderId: '852476349759',
    projectId: 'guess-the-footballer-db87f',
    storageBucket: 'guess-the-footballer-db87f.firebasestorage.app',
    iosBundleId: 'com.example.guessTheFootballer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl6Sai_rPGyIwzTIZFJh18DIs7F43_P3s',
    appId: '1:852476349759:ios:fcaf418ab9a9427a85178a',
    messagingSenderId: '852476349759',
    projectId: 'guess-the-footballer-db87f',
    storageBucket: 'guess-the-footballer-db87f.firebasestorage.app',
    iosBundleId: 'com.example.guessTheFootballer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3e6_o62TJ9di1P78Zxg0ySTsUmGk71VI',
    appId: '1:852476349759:web:d3e62e1b8985533b85178a',
    messagingSenderId: '852476349759',
    projectId: 'guess-the-footballer-db87f',
    authDomain: 'guess-the-footballer-db87f.firebaseapp.com',
    storageBucket: 'guess-the-footballer-db87f.firebasestorage.app',
  );
}
